# Generated by Django 4.0.3 on 2022-06-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set(),
        ),
    ]
