# Generated by Django 4.0.3 on 2022-06-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_content_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='correct',
            field=models.BooleanField(),
        ),
    ]
